spring.application.name=iot-platform
server.port=8080

# =========================
# H2 DATABASE (MEMORIA)
# =========================
spring.datasource.url=jdbc:h2:mem:iotdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.physical_naming_strategy=com.acme.iot.platform.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

documentation.application.description=IoT Platform Backend - DDD Bounded Contexts (IAM, Billing, IoT, Automation)
documentation.application.version=1.0.0