spring.application.name=iot-platform
server.port=${PORT:8080}
spring.datasource.url=jdbc:mysql://mysql-26d8aa15-upc-9ae0.g.aivencloud.com:17695/defaultdb?ssl-mode=REQUIRED&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_o-4Y71WqcfTGIwbGlyk
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.physical_naming_strategy=com.acme.iot.platform.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy
documentation.application.description=IoT Platform Backend - DDD Bounded Contexts (IAM, Billing, IoT, Automation)
documentation.application.version=1.0.0
