spring.application.name=iot-platform
server.port=8080

# ❌ DESACTIVAMOS MYSQL LOCAL
# spring.datasource.url=jdbc:mysql://localhost:3306/iotplatformdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
# spring.datasource.username=root
# spring.datasource.password=1234
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.profiles.active=test

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.physical_naming_strategy=com.acme.iot.platform.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

documentation.application.description=IoT Platform Backend - DDD Bounded Contexts (IAM, Billing, IoT, Automation)
documentation.application.version=1.0.0